### ISSUE TITLE
ODK Collect 1.1.7 Support

### ISSUE THREAD

**Issue by amarder** [SEL-Columbia/pyxform#11]
I've started a test here:

https://github.com/modilabs/pyxform/blob/develop/pyxform/tests/builder_tests.py#L14

that tests to make sure converting this file

https://github.com/modilabs/pyxform/blob/develop/pyxform/tests/example_xls/widgets.xls

generates this XForm

https://github.com/modilabs/pyxform/blob/develop/pyxform/tests/example_xls/widgets.xml

We need to complete this test to make sure all features in ODK Collect 1.1.7 can be expressed in the xls2xform syntax. I was working off of this page to test the different widgets:

http://opendatakit.org/help/form-design/examples/

I've found the ODK sample forms to be particularly useful:

http://code.google.com/p/opendatakit/source/browse?repo=forms

I think we should talk with the ODK list to make sure our widgets.xls does everything they want to show off.

**Comment by prabhasp** [comment]
I've tested everything going down but not including table-list. @nathanathan If you've tested the rest, go ahead and close. If not, I'll continue the test process..

**Comment by nathanathan** [comment]
I've tested everything in the spreadsheet for the new spec. However, I have not tested all features in ODK Collect 1.1.7

**Comment by prabhasp** [comment]
What we want to do is to make sure that all the screens from

http://opendatakit.org/help/form-design/examples/

are producible from excel, and keep adding onto widgets.xls and widgets.xml
until that happens..

**Comment by prabhasp** [comment]
See widgets.xls and widgets.xml in https://github.com/modilabs/pyxform/tree/nathanathan_merge/pyxform/tests/example_xls

Two issues left:
(1) don't add a 'select all that apply' hint to all select_all options within a select_all field-list; see the last after loading xml on ODK, and compare to http://opendatakit.org/wp-content/uploads/static/form-design/images-scaled/multichoicelist.png (should we think about removing this in general?)
(2) for field-lists, how do we set a title the list of choices? (ie, how do you specify the text "Multi Choice List" in http://opendatakit.org/wp-content/uploads/static/form-design/images-scaled/multichoicelist.png or "Labeled Choices" in http://opendatakit.org/wp-content/uploads/static/form-design/images-scaled/labeledchoices.png)?

**Comment by nathanathan** [comment]
I think both of these issues can be resolved by using the new "table_list" appearance instead of "field_list". (I'm not sure if it completely resolves the first, so that might be something we need to fix.)

The desired appearance can also be achieved using a field-list as follows: add an extra "select all that apply" question to the beginning of the field-list group with its appearance column set to "label" then set the appearance columns of all the choices to "list_nolabel". table-list is essentially a macro for doing this.

**Comment by prabhasp** [comment]
Okay, (2) is resolved then; (I've updated widgets.xls with both methods of doing things). (1) copied from above is still an issue even when using table-list.

(1) don't add a 'select all that apply' hint to all select_all options within a select_all field-list; see the last after loading xml on ODK, and compare to http://opendatakit.org/wp-content/uploads/static/form-design/images-scaled/multichoicelist.png (should we think about removing this in general?)

**Comment by prabhasp** [comment]
Closing this issue, and making the default select all that apply hint its own issue.
