### ISSUE TITLE
add support for type=geoshape and type=geotrace

### ISSUE THREAD

**Issue by MartijnR** [SEL-Columbia/pyxform#114]
type=geoshape produces a regular `<input>` with:

`<bind nodeset="PATH"  type="geoshape" />`

type=geoline produces a regular '<input>` with:

`<bind nodeset="PATH" type="geotrace" />`

@mitchellsundt is adding support to the javarosa libraries (and thus ODK Validate), so we may have to wait for that.

[Relevant Discussion on ODK Dev forum](https://groups.google.com/forum/#!topic/opendatakit-developers/AfVgKcpE6Jk)

**Comment by MartijnR** [comment]
@mberg @larryweya 

This should be good to go now. Mitch has done his part and pushed updates to the code tree for ODK Validate (you may have to build this - hope that's okay).

This is a test form you could use https://docs.google.com/a/enketo.org/spreadsheet/ccc?key=0Al3Mw5sknZoPdE5Wc0cwTVFnRkxTei1pMzZBZWhnRHc&usp=drive_web#gid=0

**Comment by MartijnR** [comment]
edited issue to reflect name change from `geoline` to `geotrace` in XForm (as well as XLSForm I guess)

**Comment by MartijnR** [comment]
bump!

**Comment by MartijnR** [comment]
Never mind, Mitch has done it now (and it's live on opendatakit.org). You just need to pull it in (and add support for the datatype to Formhub/Ona?)

**Comment by mberg** [comment]
Ok cool. Dickson has been busy adding in the dynamic select support to
pyxform main as there wasn't unit tests etc. so that's something we can
start to look at using too. Dickson was starting on the geostuff this week
so the timing is good
