### ISSUE TITLE
Change syntax for ${..} within the calculate column

### ISSUE THREAD

**Issue by prabhasp** [SEL-Columbia/pyxform#13]
(Will only start applying once nathanathan's changes are merged in).
For formulas within the calculate column, referrals to other instane values have to be specified in a super-awkward syntax, such as:

```
if(selected('${status}','new_user'), '${method_t}', '${method_p}')
```

(see https://docs.google.com/spreadsheet/ccc?key=0AqkhmY48RtzudENJOTBhWmRNMnpPVWdPODV2cU5yVGc )

I think we should change the syntax so that

```
if(selected(${status}, 'new_user'), ${method_t}, ${method_p})
```

is accepted (ie, remove quotes around ${..}), as that fits better with the syntax in the rest of xlsforms.

**Comment by nathanathan** [comment]
I don't think the quotes are always necessary. For example, I had no problems using this formula: selected(${mgso4_concentration_option}, 'other')
I would recommend leaving ${var} alone. If it does something more complicated than a simple find and replace there could be strange edge cases.

**Comment by prabhasp** [comment]
Very interesting.. I tested the same formula that wasn't working for me before, and now it seems to be working. Can't immediately come up with an explanation (haven't changed the code base), but closing the issue for now.
