### ISSUE TITLE
Allow notes by ignoring rows without type and name?

### ISSUE THREAD

**Issue by pld** [SEL-Columbia/pyxform#16]
In order to allow notes let users have a _Category column with text and all other columns empty.  Currently, this returns a "row N missing data type"

Trying to figure out the best way to tell that the row is just notation.  Would that it has an empty type and name be good enough?

**Comment by prabhasp** [comment]
Yes, seems like a reasonable addition. Lets require empty type,name,label columns, as those are the essential elements that are needed to define a question.

**Comment by pld** [comment]
Here's an example form, https://docs.google.com/spreadsheet/ccc?key=0AsxCVaZcfyTadGhkdk45WklOS0hFcUZiYUJQNllQakE, which fails with the error `Question with no type on row 2`

It will pass if cell A2 is moved to cell A3.
