### ISSUE TITLE
or_other doesn't apply on a per-question basis; make it so

### ISSUE THREAD

**Issue by prabhasp** [SEL-Columbia/pyxform#25]
the following form

```
(SURVEY)
type                               name      label

select_one options or_other        rank1    What is your favorite color?
select_one options                 rank2    What is your second favorite color?

(CHOICES)
list name        name               label

options           red                   Red
options           blue                   Blue
```

will add the "other" option to the `rank2` question as well (although not a separate question asking to specify other). Looks like the `options` list is being changed globally; it should be changed on a per-question bases.

**Comment by nathanathan** [comment]
Hey Prabhas, Could you send me the xls file you were using so I can quickly track this down?
