### ISSUE TITLE
Convert cascading selects to support new xform-native cascading selects

### ISSUE THREAD

**Issue by prabhasp** [SEL-Columbia/pyxform#49]
see http://opendatakit.org/help/form-design/cascading-selects/

**Comment by nathanathan** [comment]
Hi Prabhas,
There is ODK 1.2 cascading select support in the UW-ICTD branch. (Also some bug fixes I hope you'll take a look at).
However, the syntax is different, there is no cascading select sheet. It's based on adding a "choice_filter" formula to standard select questions. It's documented in the cascading select section here:
http://opendatakit.org/help/form-design/xlsform/

**Comment by ukanga** [comment]
merged in
