### ISSUE TITLE
xslx or other GDocs export format support ?

### ISSUE THREAD

**Issue by MartijnR** [SEL-Columbia/pyxform#56]
(my) GDocs no longer allows export in xls

**Comment by nathanathan** [comment]
Same here. I'll work on adding xlsx support to the UW-ICTD branch when I get a chance. I'm planning to use this lib:
http://packages.python.org/openpyxl/index.html
I would like to add ods support as well but I'm having more trouble finding a easy way to do it.

**Comment by nathanathan** [comment]
I found out openpyxl has some problems handling unicode. But no matter, I discovered the latest version of xlrd (0.8.0) now supports xlsx, so xlsx support ended up being trivial to add. This is the commit for it:
https://github.com/UW-ICTD/pyxform/commit/ae10dabbea8b1b64136425deb6714670f649f4f7
