### ISSUE TITLE
table-list for group of integers should pass

### ISSUE THREAD

**Issue by prabhasp** [SEL-Columbia/pyxform#58]
see https://www.dropbox.com/s/3c4mn2oo15ns69s/table-list-error.xls
the table-list appearance causes the group to fail because it checks that the next two selects are of the same type. however, the selects that it is enforcing need to be of the same type are not in the table-list group.

could possibly also fixed by a better error message.

**Comment by nathanathan** [comment]
I believe this has been fixed. I can't reproduce the error with the linked form.
