### ISSUE TITLE
Support xpath expressions in the repeat_count column.

### ISSUE THREAD

**Issue by nathanathan** [SEL-Columbia/pyxform#75]
The jr:count attribute requires a xpath reference (as opposed to an xpath expression), which makes it so you can't just enter an integer number of times to repeat a repeat group. I think it might be wise to auto-generate fields from the repeat_count column so integers can be used in it.

[Related issue on the ODK mailing list](https://groups.google.com/forum/?fromgroups=#!searchin/opendatakit/nathan/opendatakit/vM6LqRXVbxw/RPTJfi-9fg0J)

**Comment by prabhasp** [comment]
:+1:
