### ISSUE TITLE
Add spaces around translation of ${...} into a nodename.

### ISSUE THREAD

**Issue by prabhasp** [SEL-Columbia/pyxform#77]
See https://groups.google.com/forum/#!topic/formhub-users/jdl5FKtCvMg
User had to change `${daily_revenues}-${daily_cogs}` to: `${daily_revenues} - ${daily_cogs}` to make it work. Otherwise, javarosa interprets it as a hyphenated node name.

**Comment by nathanathan** [comment]
This issue is already on the tracker and has been fixed in the UW-ICTD
repo. See:
https://github.com/modilabs/pyxform/issues/74

**Comment by prabhasp** [comment]
Okay, closing as duplicate then.
