### ISSUE TITLE
multiple choice values should not contain spaces.

### ISSUE THREAD

**Issue by amarder** [SEL-Columbia/pyxform#8]

**Comment by amarder** [comment]
Select all that apply questions store the results as a space delimited list so it's important that values don't have any spaces in them. This should be enforced by a validation method (it may be already).

**Comment by nathanathan** [comment]
I just checked and this isn't enforced.

**Comment by prabhasp** [comment]
+0 that we enforce this.... it seems to me that the exports will be broken if there is such a thing.
