### ISSUE TITLE
This form has an error that suggests incorrect translation

### ISSUE THREAD

**Issue by prabhasp** [SEL-Columbia/pyxform#83]
[This file])(https://formhub-users.googlegroups.com/attach/a28ca81cf08877b6/GS_OM_HEALTH_FACILITY_XFORM_2013_03_20.xls?gda=TUxTFUcAAACZ7FMG4c7am4vH0KM6GiQBF7RRtTS4WDqQ7rpS-uepCWN90Yi7Ve6Aqwe70V34jUobQwFxJw55cVwemAxM-EWmeV4duv6pDMGhhhZdjQlNAw&pli=1&part=4) produces the following ODK Validate error:

```
ODK Validate Errors: Invalid XPath expression [if((/GS_OM_HEALTH_FACILITY_XFORM_2013_03_20/HF700_2 != -9990) and?(/GS_OM_HEALTH_FACILITY_XFORM_2013_03_20/HF701_2 != -9990), /GS_OM_HEALTH_FACILITY_XFORM_2013_03_20/HF701_2 + /GS_OM_HEALTH_FACILITY_XFORM_2013_03_20/HF700_2, -9990)]! java.lang.NullPointerException java.lang.NullPointerException at org.javarosa.core.model.FormDef.addTriggerable(FormDef.java:524) ...
```

note that the `and` has been transformed into `and?` : that seems to be generating the error. Looks like a pyxform bug.... whats going on?

**Comment by nathanathan** [comment]
The space after the `and` has a different character code than a normal space. It might have come from an `&nbsp;` html entity. We could do some extra string sanitizing in xlsform to avoid future errors like this.

**Comment by prabhasp** [comment]
@nathanathan thanks for the pointer! I'll leave this issue open, to inspire you or @ukanga to attempt some sanitizing :)

**Comment by nathanathan** [comment]
I added a fix for this particular issue:
https://github.com/UW-ICTD/pyxform/commit/c3a98c9e919414c75d69cb17159f9ac2c94ff558

**Comment by ukanga** [comment]
@nathanathan merged in, thanks.
